"""Generic plotting helpers for pyna objects."""

from pyna.plot.island import plot_island, island_section_points
from pyna.plot.island_chain import plot_island_chain, island_chain_section_points
from pyna.plot.xo_points import draw_xo_points, XO_STYLE
from pyna.plot.poincare import plot_poincare, plot_poincare_data
from pyna.plot.poincare_beta import plot_poincare_beta_grid
from pyna.plot.beta_ramp import (
    beta_physics_rows,
    beta_ramp_scan_rows,
    plot_beta_physics_dashboard,
    plot_beta_ramp_scan_summary,
    read_beta_physics_csv,
)
from pyna.plot.boundary_island import plot_boundary_island_sections
from pyna.plot.rmp import (
    draw_pest_grid,
    draw_rmp_island_width_bars,
    draw_reduced_stable_manifolds,
    draw_resonant_surfaces,
    draw_rmp_fixed_points,
    draw_rmp_resonance_section,
    plot_rmp_resonance_sections,
)
from pyna.plot.mgrid import (
    draw_smooth_pest_grid,
    plot_mgrid_current_cylindrical_components,
    plot_pest_current_components,
    plot_surface_fourier_ripple_summary,
)
from pyna.plot.section_geometry import (
    SECTION_ORBIT_COLORS,
    apply_section_limits,
    branch_payload_point_subset,
    branch_payload_smax,
    clip_branch_payloads_by_arclength,
    contiguous_prefix_mask,
    create_section_grid,
    orbit_identity,
    orbit_list,
    orbit_point_arrays,
    orbits_for_section,
    draw_axis_point,
    draw_branch_manifold_lines,
    draw_fixed_point_orbits,
    draw_orbit_points,
    draw_manifold_lines,
    draw_manifold_origins,
    draw_manifold_points,
    draw_poincare_background,
    draw_poincare_background_by_seed_value,
    draw_poincare_points,
    draw_wall_section,
    format_section_axis,
    map_order_value,
    manifold_lpol_max,
    manifolds_for_section,
    poincare_seed_values_for_points,
    save_figure,
    section_data_limits,
    trim_compact_tick_labels,
)
from pyna.plot.tube import (
    plot_tube_section,
    plot_tube_chain_section,
    plot_tube_chain_poincare,
    tube_legend_handles,
    TUBE_COLORS,
    TUBE_MARKERS_O,
    TUBE_MARKERS_X,
)
from pyna.plot.j_streamlines import (
    PestSeededStreamlines,
    PestSurfaceFaceFluxes,
    VmecCurrentFourier,
    pest_tangent_components_to_cylindrical,
    plot_j_streamline_seed_sections,
    plot_j_streamlines_on_pest_surface_plotly,
    trace_j_streamlines_on_pest,
    vmec_current_fourier_to_pest_field,
)

__all__ = [
    # Island / IslandChain
    "plot_island",
    "island_section_points",
    "plot_island_chain",
    "island_chain_section_points",
    "draw_xo_points",
    "XO_STYLE",
    "plot_poincare",
    "plot_poincare_data",
    "plot_poincare_beta_grid",
    "beta_physics_rows",
    "beta_ramp_scan_rows",
    "plot_beta_physics_dashboard",
    "plot_beta_ramp_scan_summary",
    "read_beta_physics_csv",
    "plot_boundary_island_sections",
    "draw_pest_grid",
    "draw_rmp_island_width_bars",
    "draw_reduced_stable_manifolds",
    "draw_resonant_surfaces",
    "draw_rmp_fixed_points",
    "draw_rmp_resonance_section",
    "plot_rmp_resonance_sections",
    "draw_smooth_pest_grid",
    "plot_mgrid_current_cylindrical_components",
    "plot_pest_current_components",
    "plot_surface_fourier_ripple_summary",
    "SECTION_ORBIT_COLORS",
    "apply_section_limits",
    "branch_payload_point_subset",
    "branch_payload_smax",
    "clip_branch_payloads_by_arclength",
    "contiguous_prefix_mask",
    "create_section_grid",
    "orbit_identity",
    "orbit_list",
    "orbit_point_arrays",
    "orbits_for_section",
    "draw_axis_point",
    "draw_branch_manifold_lines",
    "draw_fixed_point_orbits",
    "draw_orbit_points",
    "draw_manifold_lines",
    "draw_manifold_origins",
    "draw_manifold_points",
    "draw_poincare_background",
    "draw_poincare_background_by_seed_value",
    "draw_poincare_points",
    "draw_wall_section",
    "format_section_axis",
    "map_order_value",
    "manifold_lpol_max",
    "manifolds_for_section",
    "poincare_seed_values_for_points",
    "save_figure",
    "section_data_limits",
    "trim_compact_tick_labels",
    # Tube / TubeChain (first-class)
    "plot_tube_section",
    "plot_tube_chain_section",
    "plot_tube_chain_poincare",
    "tube_legend_handles",
    "TUBE_COLORS",
    "TUBE_MARKERS_O",
    "TUBE_MARKERS_X",
    "PestSeededStreamlines",
    "PestSurfaceFaceFluxes",
    "VmecCurrentFourier",
    "pest_tangent_components_to_cylindrical",
    "plot_j_streamline_seed_sections",
    "plot_j_streamlines_on_pest_surface_plotly",
    "trace_j_streamlines_on_pest",
    "vmec_current_fourier_to_pest_field",
]
