from pathlib import Path

p = Path(r'C:\Users\Legion\Nutstore\1\Repo\pyna\pyna\topo\island_healed_coords.py')
text = p.read_text(encoding='utf-8', errors='replace').replace('\r\n', '\n')

# 1) add adapter before make_xcyc_anchors
marker = '# ---------------------------------------------------------------------------\n# Factory: build XOCycAnchor list from IslandChainOrbit objects\n# ---------------------------------------------------------------------------\n'
insert = '''# ---------------------------------------------------------------------------\n# Adapter: convert IslandChainOrbit objects to fp_by_section dict\n# ---------------------------------------------------------------------------\n\ndef fp_by_section_from_orbits(\n    xring_orbit,\n    oring_orbit,\n    phi_sections: Optional[List[float]] = None,\n    phi_tol: float = 0.05,\n) -> dict:\n    """Convert X/O IslandChainOrbit objects to fp_by_section format.\n\n    Returns\n    -------\n    dict\n        Mapping phi -> {'xpts': [...], 'opts': [...]} where entries are\n        ChainFixedPoint objects (already exposing .R / .Z).\n    """\n    xfps = list(getattr(xring_orbit, 'fixed_points', []))\n    ofps = list(getattr(oring_orbit, 'fixed_points', []))\n\n    if phi_sections is None:\n        phis = sorted({float(fp.phi) % (2 * np.pi) for fp in xfps + ofps})\n    else:\n        phis = [float(phi) % (2 * np.pi) for phi in phi_sections]\n\n    out = {}\n    for phi in phis:\n        xs = []\n        os = []\n        for fp in xfps:\n            dphi = np.angle(np.exp(1j * ((float(fp.phi) % (2 * np.pi)) - phi)))\n            if abs(dphi) <= phi_tol:\n                xs.append(fp)\n        for fp in ofps:\n            dphi = np.angle(np.exp(1j * ((float(fp.phi) % (2 * np.pi)) - phi)))\n            if abs(dphi) <= phi_tol:\n                os.append(fp)\n        out[phi] = {'xpts': xs, 'opts': os}\n    return out\n\n\n'''
if insert not in text:
    text = text.replace(marker, insert + marker)

# 2) make trajectory_npz optional + add orbit args + cycle_weight
old_sig = '''def build_from_trajectory_npz(\n    coords_npz: str,\n    trajectory_npz: str,\n    r_inner_fit: float = 0.82,\n    r_island: float = 1.0,\n    blend_width: float = 0.12,\n    n_fourier: int = 8,\n    theta_X: float = np.pi,\n    theta_O: float = 0.0,\n    n_anchors: int = 40,\n    fp_by_section: dict | None = None,\n    r_geom_min: float = 0.05,\n) -> \'IslandHealedCoordMap\':'''
new_sig = '''def build_from_trajectory_npz(\n    coords_npz: str,\n    trajectory_npz: str | None = None,\n    xring_orbit = None,\n    oring_orbit = None,\n    r_inner_fit: float = 0.82,\n    r_island: float = 1.0,\n    blend_width: float = 0.12,\n    n_fourier: int = 8,\n    theta_X: float = np.pi,\n    theta_O: float = 0.0,\n    n_anchors: int = 40,\n    fp_by_section: dict | None = None,\n    r_geom_min: float = 0.05,\n    cycle_weight: float = 200.0,\n) -> \'IslandHealedCoordMap\':'''
text = text.replace(old_sig, new_sig)

# 3) insert orbit-derived fp_by_section logic after phi_vals block
old_block = """    n_phi = len(phi_vals)\n\n    # ── Build sections using unified Fourier representation ───────────────\n"""
new_block = """    n_phi = len(phi_vals)\n\n    # If orbit objects are provided, convert them to per-section fixed-point dict.\n    if fp_by_section is None and xring_orbit is not None and oring_orbit is not None:\n        fp_by_section = fp_by_section_from_orbits(\n            xring_orbit, oring_orbit, phi_sections=list(phi_vals), phi_tol=0.08\n        )\n\n    # ── Build sections using unified Fourier representation ───────────────\n"""
text = text.replace(old_block, new_block)

# 4) replace trajectory loading block with dual path (orbits/trajectory)
old_traj_block = '''    # ── Load X/O ring trajectories ────────────────────────────────────────\n    t = np.load(trajectory_npz)\n    phi_traj = t['phi_arr']   # (N,) in [0, 2pi)\n    R_x_traj = t['R_x_arr']\n    Z_x_traj = t['Z_x_arr']\n    R_o_traj = t['R_o_arr']\n    Z_o_traj = t['Z_o_arr']\n\n    # Interpolators for continuous X/O positions vs phi\n    from scipy.interpolate import interp1d as _interp1d\n    _Rx_itp = _interp1d(phi_traj, R_x_traj, kind='cubic', fill_value='extrapolate')\n    _Zx_itp = _interp1d(phi_traj, Z_x_traj, kind='cubic', fill_value='extrapolate')\n    _Ro_itp = _interp1d(phi_traj, R_o_traj, kind='cubic', fill_value='extrapolate')\n    _Zo_itp = _interp1d(phi_traj, Z_o_traj, kind='cubic', fill_value='extrapolate')\n'''
new_traj_block = '''    # ── Load / derive continuous X/O ring trajectories ────────────────────\n    from scipy.interpolate import interp1d as _interp1d\n\n    if xring_orbit is not None and oring_orbit is not None:\n        xfps = sorted(list(getattr(xring_orbit, 'fixed_points', [])), key=lambda fp: float(fp.phi))\n        ofps = sorted(list(getattr(oring_orbit, 'fixed_points', [])), key=lambda fp: float(fp.phi))\n        phi_x = np.array([float(fp.phi) for fp in xfps], dtype=float)\n        R_x_traj = np.array([float(fp.R) for fp in xfps], dtype=float)\n        Z_x_traj = np.array([float(fp.Z) for fp in xfps], dtype=float)\n        phi_o = np.array([float(fp.phi) for fp in ofps], dtype=float)\n        R_o_traj = np.array([float(fp.R) for fp in ofps], dtype=float)\n        Z_o_traj = np.array([float(fp.Z) for fp in ofps], dtype=float)\n\n        if len(phi_x) < 2 or len(phi_o) < 2:\n            raise ValueError('Orbit path requires >=2 fixed points in both xring_orbit and oring_orbit.')\n\n        _Rx_itp = _interp1d(phi_x, R_x_traj, kind='linear', fill_value='extrapolate')\n        _Zx_itp = _interp1d(phi_x, Z_x_traj, kind='linear', fill_value='extrapolate')\n        _Ro_itp = _interp1d(phi_o, R_o_traj, kind='linear', fill_value='extrapolate')\n        _Zo_itp = _interp1d(phi_o, Z_o_traj, kind='linear', fill_value='extrapolate')\n    else:\n        if trajectory_npz is None:\n            raise ValueError('Need either trajectory_npz or both xring_orbit and oring_orbit.')\n        t = np.load(trajectory_npz)\n        phi_traj = t['phi_arr']\n        R_x_traj = t['R_x_arr']\n        Z_x_traj = t['Z_x_arr']\n        R_o_traj = t['R_o_arr']\n        Z_o_traj = t['Z_o_arr']\n        _Rx_itp = _interp1d(phi_traj, R_x_traj, kind='cubic', fill_value='extrapolate')\n        _Zx_itp = _interp1d(phi_traj, Z_x_traj, kind='cubic', fill_value='extrapolate')\n        _Ro_itp = _interp1d(phi_traj, R_o_traj, kind='cubic', fill_value='extrapolate')\n        _Zo_itp = _interp1d(phi_traj, Z_o_traj, kind='cubic', fill_value='extrapolate')\n'''
text = text.replace(old_traj_block, new_traj_block)

# 5) add new high-level builder near end of file if not present
append_marker = """    return IslandHealedCoordMap(\n        sections=sections,\n        anchors=anchors,\n        r_inner_fit=r_inner_fit,\n        r_island=r_island,\n        blend_width=blend_width,\n        theta_X=theta_X,\n        theta_O=theta_O,\n    )\n"""
add_block = '''\n\ndef build_from_orbits(\n    coords_npz: str,\n    xring_orbit,\n    oring_orbit,\n    r_inner_fit: float = 0.82,\n    r_island: float = 1.0,\n    blend_width: float = 0.12,\n    n_fourier: int = 8,\n    theta_X: float = np.pi,\n    theta_O: float = 0.0,\n    n_anchors: int = 40,\n    r_geom_min: float = 0.05,\n    cycle_weight: float = 200.0,\n) -> 'IslandHealedCoordMap':\n    """High-level convenience wrapper: build healed map directly from orbit objects."""\n    return build_from_trajectory_npz(\n        coords_npz=coords_npz,\n        trajectory_npz=None,\n        xring_orbit=xring_orbit,\n        oring_orbit=oring_orbit,\n        r_inner_fit=r_inner_fit,\n        r_island=r_island,\n        blend_width=blend_width,\n        n_fourier=n_fourier,\n        theta_X=theta_X,\n        theta_O=theta_O,\n        n_anchors=n_anchors,\n        fp_by_section=None,\n        r_geom_min=r_geom_min,\n        cycle_weight=cycle_weight,\n    )\n'''
if add_block not in text:
    text = text.replace(append_marker, append_marker + add_block)

p.write_text(text, encoding='utf-8')
print('patched island_healed_coords.py')
