import json

nb = json.load(open('notebooks/tutorials/rmp_island_validation_solovev.ipynb', encoding='utf-8'))
code_cells = [(i, c) for i, c in enumerate(nb['cells']) if c['cell_type'] == 'code']

# ── Fix 1: Code cell 6 (Poincaré tracing) ───────────────────────────────────
new_cell6_src = [
    "import json as _json, pathlib as _pathlib\n",
    "_CACHE = _pathlib.Path(\"pyna_output/poincare_solovev.json\")\n",
    "_CACHE.parent.mkdir(exist_ok=True)\n",
    "\n",
    "if _CACHE.exists():\n",
    "    _d = _json.loads(_CACHE.read_text())\n",
    "    pts_all = np.array(_d[\"pts\"])\n",
    "    print(f\"Loaded {len(pts_all)} crossings from cache.\")\n",
    "else:\n",
    "    # Launch field lines bracketing q=2/1 surface\n",
    "    n_lines = 5  # reduced for tutorial speed\n",
    "    psi_arr = np.linspace(max(psi_res - 0.06, 0.01), min(psi_res + 0.06, 0.95), n_lines)\n",
    "    start_pts = np.column_stack([\n",
    "        R_ax + np.sqrt(psi_arr) * eq.a,\n",
    "        np.zeros(n_lines),\n",
    "        np.zeros(n_lines),\n",
    "    ])\n",
    "\n",
    "    section = ToroidalSection(phi0=0.0)\n",
    "    tracer = FieldLineTracer(field_func, dt=0.05)\n",
    "\n",
    "    print(f\"Tracing {n_lines} field lines (t_max=100)...\")\n",
    "    trajs = tracer.trace_many(start_pts, t_max=100.0)\n",
    "\n",
    "    pmap = PoincareMap([section])\n",
    "    for traj in trajs:\n",
    "        pmap.record_trajectory(traj)\n",
    "\n",
    "    pts_all = pmap.crossing_array(0)\n",
    "    _CACHE.write_text(_json.dumps({\"pts\": pts_all.tolist()}))\n",
    "    print(f\"Computed {len(pts_all)} crossings, cached.\")\n",
    "\n",
    "print(f\"Total Poincar\u00e9 crossings: {len(pts_all)}\")\n",
]
nb_idx6, cell6 = code_cells[6]
cell6['source'] = new_cell6_src

# ── Fix 2: Code cell 11 (manifolds for RMP island) ──────────────────────────
# Change n_turns=3 -> 2, add rtol/atol
nb_idx11, cell11 = code_cells[11]
src11 = ''.join(cell11['source'])
src11 = src11.replace(
    'sm.grow(n_turns=3, init_length=1e-4, n_init_pts=3, both_sides=True)',
    'sm.grow(n_turns=2, init_length=1e-4, n_init_pts=3, both_sides=True, rtol=1e-5, atol=1e-7)'
)
src11 = src11.replace(
    'um.grow(n_turns=3, init_length=1e-4, n_init_pts=3, both_sides=True)',
    'um.grow(n_turns=2, init_length=1e-4, n_init_pts=3, both_sides=True, rtol=1e-5, atol=1e-7)'
)
cell11['source'] = [line + '\n' for line in src11.split('\n')]
# fix trailing extra newline
if cell11['source'] and cell11['source'][-1] == '\n':
    cell11['source'][-1] = ''

# ── Fix 3: Code cell 12 (single-null manifolds) — add JSON caching ──────────
nb_idx12, cell12 = code_cells[12]

new_cell12_src = [
    "# =========================================================================\n",
    "# Single-null divertor equilibrium: separatrix X-point & stable/unstable manifolds\n",
    "# =========================================================================\n",
    "\n",
    "import json as _json, pathlib as _pathlib\n",
    "from pyna.MCF.equilibrium.Solovev import solovev_single_null\n",
    "from pyna.topo.variational import PoincareMapVariationalEquations\n",
    "from pyna.topo.manifold_improve import StableManifold, UnstableManifold\n",
    "from pyna.MCF.visual.tokamak_manifold import _manifold_line_collection\n",
    "\n",
    "_CACHE_SN = _pathlib.Path(\"pyna_output/solovev_sn_manifolds.json\")\n",
    "_CACHE_SN.parent.mkdir(exist_ok=True)\n",
    "\n",
    "# -----------------------------------------------------------------------\n",
    "# 1. Build single-null equilibrium (fast, <0.1s)\n",
    "# -----------------------------------------------------------------------\n",
    "eq_sn = solovev_single_null(\n",
    "    R0=1.86, a=0.595, B0=5.3,\n",
    "    kappa=1.8, delta_u=0.33, delta_l=0.40, kappa_x=1.5,\n",
    "    q0=1.5,\n",
    ")\n",
    "R_ax_sn, Z_ax_sn = eq_sn.magnetic_axis\n",
    "print(f'Magnetic axis: R={R_ax_sn:.4f} m  Z={Z_ax_sn:.4f} m')\n",
    "\n",
    "# -----------------------------------------------------------------------\n",
    "# 2. Locate X-point (analytic from equilibrium)\n",
    "# -----------------------------------------------------------------------\n",
    "R_xpt_sn, Z_xpt_sn = eq_sn.find_xpoint()\n",
    "psi_at_x = float(eq_sn.psi(np.array([R_xpt_sn]), np.array([Z_xpt_sn]))[0])\n",
    "print(f'X-point: R={R_xpt_sn:.6f}  Z={Z_xpt_sn:.6f}  psi={psi_at_x:.6f}')\n",
    "\n",
    "if _CACHE_SN.exists():\n",
    "    _d = _json.loads(_CACHE_SN.read_text())\n",
    "    det_sn = _d[\"det_J\"]\n",
    "    lam_abs_sn = [_d[\"lam_stable\"], _d[\"lam_unstable\"]]\n",
    "    sm_segs = [np.array(s) for s in _d[\"sm_segments\"]]\n",
    "    um_segs = [np.array(s) for s in _d[\"um_segments\"]]\n",
    "    print(f\"Loaded manifolds from cache. det(J)={det_sn:.6f}\")\n",
    "else:\n",
    "    # -----------------------------------------------------------------------\n",
    "    # 3. Define 2-D field-line ODE  dR/dphi, dZ/dphi\n",
    "    # -----------------------------------------------------------------------\n",
    "    def field_func_sn(rzphi):\n",
    "        R, Z = float(rzphi[0]), float(rzphi[1])\n",
    "        BR, BZ = eq_sn.BR_BZ(np.array([R]), np.array([Z]))\n",
    "        Bphi  = eq_sn.Bphi(np.array([R]))\n",
    "        BR_t, BZ_t, Bp_t = float(BR[0]), float(BZ[0]), float(Bphi[0])\n",
    "        B_mag = np.sqrt(BR_t**2 + BZ_t**2 + Bp_t**2) + 1e-30\n",
    "        return np.array([BR_t/B_mag, BZ_t/B_mag, Bp_t/(R*B_mag)])\n",
    "\n",
    "    def field_func_2d_sn(R, Z, phi):\n",
    "        t = field_func_sn(np.array([R, Z, phi]))\n",
    "        if abs(t[2]) < 1e-15:\n",
    "            return np.array([0.0, 0.0])\n",
    "        return np.array([t[0]/t[2], t[1]/t[2]])\n",
    "\n",
    "    # -----------------------------------------------------------------------\n",
    "    # 4. Compute monodromy matrix J at the X-point\n",
    "    # -----------------------------------------------------------------------\n",
    "    phi_span_sn = (0.0, 2.0 * np.pi)\n",
    "    vq_sn = PoincareMapVariationalEquations(field_func_2d_sn, fd_eps=1e-5)\n",
    "    xpt_sn = np.array([R_xpt_sn, Z_xpt_sn])\n",
    "    Jac_sn = vq_sn.jacobian_matrix(\n",
    "        xpt_sn, phi_span_sn,\n",
    "        solve_ivp_kwargs=dict(method='RK45', rtol=1e-6, atol=1e-8),\n",
    "    )\n",
    "    lam_sn = np.linalg.eigvals(Jac_sn)\n",
    "    lam_abs_sn = sorted(np.abs(lam_sn))\n",
    "    det_sn = float(np.linalg.det(Jac_sn))\n",
    "    print(f'det(J) = {det_sn:.8f}  (ideal = 1.0 for area-preserving)')\n",
    "    print(f'|lambda_stable|   = {lam_abs_sn[0]:.6f}')\n",
    "    print(f'|lambda_unstable| = {lam_abs_sn[1]:.6f}')\n",
    "\n",
    "    # -----------------------------------------------------------------------\n",
    "    # 5. Grow stable / unstable manifolds\n",
    "    # -----------------------------------------------------------------------\n",
    "    RZlimit_sn = (eq_sn.R0 - 1.6*eq_sn.a, eq_sn.R0 + 1.6*eq_sn.a,\n",
    "                  -2.2*eq_sn.kappa*eq_sn.a, 1.8*eq_sn.kappa*eq_sn.a)\n",
    "    sm_sn = StableManifold(xpt_sn, Jac_sn, field_func_2d_sn, phi_span=phi_span_sn)\n",
    "    um_sn = UnstableManifold(xpt_sn, Jac_sn, field_func_2d_sn, phi_span=phi_span_sn)\n",
    "    ivp_kw = dict(rtol=1e-5, atol=1e-7)\n",
    "    sm_sn.grow(n_turns=2, init_length=1e-4, n_init_pts=3, both_sides=True,\n",
    "               RZlimit=RZlimit_sn, **ivp_kw)\n",
    "    um_sn.grow(n_turns=2, init_length=1e-4, n_init_pts=3, both_sides=True,\n",
    "               RZlimit=RZlimit_sn, **ivp_kw)\n",
    "    print(f'Stable   segments: {len(sm_sn.segments)}')\n",
    "    print(f'Unstable segments: {len(um_sn.segments)}')\n",
    "\n",
    "    sm_segs = [s for s in sm_sn.segments if len(s) >= 2]\n",
    "    um_segs = [s for s in um_sn.segments if len(s) >= 2]\n",
    "    _CACHE_SN.write_text(_json.dumps({\n",
    "        \"det_J\": det_sn,\n",
    "        \"lam_stable\": float(lam_abs_sn[0]),\n",
    "        \"lam_unstable\": float(lam_abs_sn[1]),\n",
    "        \"sm_segments\": [seg.tolist() for seg in sm_segs],\n",
    "        \"um_segments\": [seg.tolist() for seg in um_segs],\n",
    "    }))\n",
    "    print(f\"Computed and cached. det(J)={det_sn:.6f}\")\n",
    "\n",
    "# -----------------------------------------------------------------------\n",
    "# 6. Plot: equilibrium + X-point manifolds\n",
    "# -----------------------------------------------------------------------\n",
    "R_range_sn = (eq_sn.R0 - 1.6*eq_sn.a, eq_sn.R0 + 1.6*eq_sn.a)\n",
    "Z_range_sn = (-2.2*eq_sn.kappa*eq_sn.a, 1.8*eq_sn.kappa*eq_sn.a)\n",
    "R1d_sn = np.linspace(*R_range_sn, 300)\n",
    "Z1d_sn = np.linspace(*Z_range_sn, 300)\n",
    "Rg_sn, Zg_sn = np.meshgrid(R1d_sn, Z1d_sn)\n",
    "psi_g_sn = eq_sn.psi(Rg_sn, Zg_sn)\n",
    "\n",
    "fig, axes = plt.subplots(1, 2, figsize=(13, 6))\n",
    "\n",
    "# Left: flux contours\n",
    "ax = axes[0]\n",
    "cs = ax.contour(Rg_sn, Zg_sn, psi_g_sn,\n",
    "                levels=np.linspace(0.05, 0.95, 14), cmap='RdYlBu_r', linewidths=0.7)\n",
    "ax.contour(Rg_sn, Zg_sn, psi_g_sn, levels=[1.0], colors='k', linewidths=2.0)\n",
    "ax.plot(R_ax_sn, Z_ax_sn,  '+k', ms=10, mew=2, label='O-point (axis)')\n",
    "ax.plot(R_xpt_sn, Z_xpt_sn, 'xr', ms=11, mew=2.5, label='X-point')\n",
    "ax.set_aspect('equal'); ax.set_xlim(R_range_sn); ax.set_ylim(Z_range_sn)\n",
    "ax.set_xlabel('R (m)'); ax.set_ylabel('Z (m)')\n",
    "ax.set_title(\"Single-null Solov'ev: flux surfaces\", fontsize=11)\n",
    "ax.legend(fontsize=9); plt.colorbar(cs, ax=ax, label=r'$\\psi_{\\rm norm}$', shrink=0.7)\n",
    "\n",
    "# Right: manifolds\n",
    "ax2 = axes[1]\n",
    "ax2.contour(Rg_sn, Zg_sn, psi_g_sn,\n",
    "            levels=np.linspace(0.1, 0.9, 10), colors='lightgray', linewidths=0.5)\n",
    "ax2.contour(Rg_sn, Zg_sn, psi_g_sn, levels=[1.0], colors='k', linewidths=1.5)\n",
    "\n",
    "s_ref_s = max((np.ptp(seg[:, 0]) for seg in sm_segs if len(seg) > 1), default=1.0)\n",
    "for seg in sm_segs:\n",
    "    if len(seg) >= 2:\n",
    "        lc, _ = _manifold_line_collection(seg, cmap='GnBu', s_ref=s_ref_s, lw=1.5)\n",
    "        ax2.add_collection(lc)\n",
    "\n",
    "s_ref_u = max((np.ptp(seg[:, 0]) for seg in um_segs if len(seg) > 1), default=1.0)\n",
    "for seg in um_segs:\n",
    "    if len(seg) >= 2:\n",
    "        lc, _ = _manifold_line_collection(seg, cmap='Oranges', s_ref=s_ref_u, lw=1.5)\n",
    "        ax2.add_collection(lc)\n",
    "\n",
    "ax2.plot(R_xpt_sn, Z_xpt_sn, 'kx', ms=12, mew=2.5, zorder=10, label='X-point')\n",
    "ax2.plot([], [], color='steelblue', lw=2, label=r'$W^s$ (stable)')\n",
    "ax2.plot([], [], color='darkorange', lw=2, label=r'$W^u$ (unstable)')\n",
    "ax2.set_aspect('equal'); ax2.set_xlim(R_range_sn); ax2.set_ylim(Z_range_sn)\n",
    "ax2.set_xlabel('R (m)'); ax2.set_ylabel('Z (m)')\n",
    "ax2.set_title(fr'Separatrix manifolds  det(J)={det_sn:.6f}', fontsize=11)\n",
    "ax2.legend(fontsize=9, loc='upper right')\n",
    "\n",
    "plt.suptitle(\"Single-null X-point: stable/unstable manifolds of Poincar\u00e9 map\", fontsize=12)\n",
    "plt.tight_layout()\n",
    "plt.savefig('solovev_single_null_manifolds.png', dpi=120, bbox_inches='tight')\n",
    "plt.show()\n",
]

cell12['source'] = new_cell12_src

with open('notebooks/tutorials/rmp_island_validation_solovev.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print("Notebook written successfully.")
