"""pyna.toroidal.visual — publication-quality toroidal equilibrium visualization."""
from .equilibrium import plot_nested_flux_surfaces, BPOL_CMAP, ISLAND_CMAPS
from .RMP_spectrum import (
    island_fixed_points,
    compose_magnetic_perturbations,
    circular_shell_divergence_diagnostic,
    fieldline_velocity_spectrum_on_circular_surface,
    rmp_nrmp_mode_rows,
    sample_stellarator_cylindrical_field,
    radial_rmp_field_template,
    DivergenceDiagnostic,
    FieldlineVelocitySpectrum,
    CoupledFixedPointSweep,
    NonResonantContributionRow,
    NonResonantFieldlineResponse,
    NonResonantResidualOrderScan,
    LogLogOrderFit,
    RMPnRMPModeRow,
    RMPAmplitudeOrderScan,
    RMPPhaseOrderScan,
    RMPResolutionConvergenceRow,
    RMPResolutionConvergenceScan,
    ResonantComponent,
    SurfaceMapResidual,
    FixedPointPhaseComparison,
    DeformedFixedPointProjection,
    deformed_surface_map_residual,
    loglog_order_fit,
    plot_perturbation_order_summary,
    rmp_fixed_point_seeds,
    rmp_closure_map_span,
    scan_nonresonant_residual_order,
    scan_coupled_fixed_point_sweep,
    scan_rmp_amplitude_order,
    scan_rmp_phase_order,
    scan_rmp_resolution_convergence,
    compare_cyna_fixed_points_for_component,
    deformed_circular_section_rz,
    project_fixed_points_to_deformed_surface,
    find_resonant_components_analytic,
    plot_island_width_bars,
    compute_mn_spectrum,
    plot_mn_heatmap,
    plot_mn_heatmap_radial,
)
from .magnetic_spectrum import (
    PoincareRationalTrace,
    RadialModeSpectrum,
    RationalSurfaceMarker,
    SectionIslandBar,
    SpectrumSurfaceMatrix,
    island_bars_on_section,
    overlay_poincare_rational_trace,
    overlay_radial_mode_island_bars,
    overlay_radial_resonance_curve,
    overlay_rational_island_bars,
    overlay_rational_surface_markers,
    overlay_surface_resonance_line,
    plot_chirikov_overlaps,
    plot_island_chains_on_section,
    plot_island_phase_scan,
    plot_radial_mode_heatmap,
    plot_radial_mode_pcolormesh,
    plot_rational_surface_map,
    plot_resonant_radial_profiles,
    plot_spectrum_bar3d,
    plot_spectrum_heatmap,
    plot_spectrum_pcolormesh,
    radial_mode_spectrum,
    rational_surface_markers,
    spectrum_surface_matrix,
)
try:
    from .tokamak_manifold import (
        plot_equilibrium_cross_section,
        plot_poincare_orbits,
        plot_xcycle_marker,
        plot_manifold_1d,
        plot_xcycle_all_manifolds,
        make_tokamak_overview_figure,
        manifold_legend_handles,
        UNSTABLE_CMAPS,
        STABLE_CMAPS,
        PUBLICATION_RC,
    )
except ModuleNotFoundError as exc:
    _TOKAMAK_MANIFOLD_IMPORT_ERROR = exc

    def _tokamak_manifold_unavailable(*args, **kwargs):
        raise ModuleNotFoundError(
            "tokamak manifold plotting requires optional dependencies that are "
            "not available in this environment"
        ) from _TOKAMAK_MANIFOLD_IMPORT_ERROR

    plot_equilibrium_cross_section = _tokamak_manifold_unavailable
    plot_poincare_orbits = _tokamak_manifold_unavailable
    plot_xcycle_marker = _tokamak_manifold_unavailable
    plot_manifold_1d = _tokamak_manifold_unavailable
    plot_xcycle_all_manifolds = _tokamak_manifold_unavailable
    make_tokamak_overview_figure = _tokamak_manifold_unavailable
    manifold_legend_handles = _tokamak_manifold_unavailable
    UNSTABLE_CMAPS = []
    STABLE_CMAPS = []
    PUBLICATION_RC = {}

__all__ = [
    "plot_nested_flux_surfaces",
    "BPOL_CMAP",
    "ISLAND_CMAPS",
    "island_fixed_points",
    "compose_magnetic_perturbations",
    "circular_shell_divergence_diagnostic",
    "fieldline_velocity_spectrum_on_circular_surface",
    "rmp_nrmp_mode_rows",
    "sample_stellarator_cylindrical_field",
    "radial_rmp_field_template",
    "DivergenceDiagnostic",
    "FieldlineVelocitySpectrum",
    "CoupledFixedPointSweep",
    "NonResonantContributionRow",
    "NonResonantFieldlineResponse",
    "NonResonantResidualOrderScan",
    "LogLogOrderFit",
    "RMPnRMPModeRow",
    "RMPAmplitudeOrderScan",
    "RMPPhaseOrderScan",
    "RMPResolutionConvergenceRow",
    "RMPResolutionConvergenceScan",
    "ResonantComponent",
    "SurfaceMapResidual",
    "FixedPointPhaseComparison",
    "DeformedFixedPointProjection",
    "deformed_surface_map_residual",
    "loglog_order_fit",
    "plot_perturbation_order_summary",
    "rmp_fixed_point_seeds",
    "rmp_closure_map_span",
    "scan_nonresonant_residual_order",
    "scan_coupled_fixed_point_sweep",
    "scan_rmp_amplitude_order",
    "scan_rmp_phase_order",
    "scan_rmp_resolution_convergence",
    "compare_cyna_fixed_points_for_component",
    "deformed_circular_section_rz",
    "project_fixed_points_to_deformed_surface",
    "find_resonant_components_analytic",
    "plot_island_width_bars",
    "compute_mn_spectrum",
    "plot_mn_heatmap",
    "plot_mn_heatmap_radial",
    "PoincareRationalTrace",
    "RadialModeSpectrum",
    "RationalSurfaceMarker",
    "SectionIslandBar",
    "SpectrumSurfaceMatrix",
    "island_bars_on_section",
    "overlay_poincare_rational_trace",
    "overlay_radial_mode_island_bars",
    "overlay_radial_resonance_curve",
    "overlay_rational_island_bars",
    "overlay_rational_surface_markers",
    "overlay_surface_resonance_line",
    "plot_chirikov_overlaps",
    "plot_island_chains_on_section",
    "plot_island_phase_scan",
    "plot_radial_mode_heatmap",
    "plot_radial_mode_pcolormesh",
    "plot_rational_surface_map",
    "plot_resonant_radial_profiles",
    "plot_spectrum_bar3d",
    "plot_spectrum_heatmap",
    "plot_spectrum_pcolormesh",
    "radial_mode_spectrum",
    "rational_surface_markers",
    "spectrum_surface_matrix",
    "plot_equilibrium_cross_section",
    "plot_poincare_orbits",
    "plot_xcycle_marker",
    "plot_manifold_1d",
    "plot_xcycle_all_manifolds",
    "make_tokamak_overview_figure",
    "manifold_legend_handles",
    "UNSTABLE_CMAPS",
    "STABLE_CMAPS",
    "PUBLICATION_RC",
]
