"""pyna.toroidal.visual — publication-quality toroidal equilibrium visualization."""
from importlib import import_module

from .equilibrium import plot_nested_flux_surfaces, BPOL_CMAP, ISLAND_CMAPS
from .RMP_spectrum import (
    island_fixed_points,
    compose_magnetic_perturbations,
    circular_shell_divergence_diagnostic,
    fieldline_velocity_spectrum_on_circular_surface,
    rmp_nrmp_mode_rows,
    sample_stellarator_cylindrical_field,
    radial_rmp_field_template,
    DivergenceDiagnostic,
    FieldlineVelocitySpectrum,
    CoupledFixedPointSweep,
    NonResonantContributionRow,
    NonResonantFieldlineResponse,
    NonResonantResidualOrderScan,
    LogLogOrderFit,
    RMPnRMPModeRow,
    RMPAmplitudeOrderScan,
    RMPPhaseOrderScan,
    RMPResolutionConvergenceRow,
    RMPResolutionConvergenceScan,
    ResonantComponent,
    SurfaceMapResidual,
    FixedPointPhaseComparison,
    DeformedFixedPointProjection,
    deformed_surface_map_residual,
    loglog_order_fit,
    plot_perturbation_order_summary,
    rmp_fixed_point_seeds,
    rmp_closure_map_span,
    scan_nonresonant_residual_order,
    scan_coupled_fixed_point_sweep,
    scan_rmp_amplitude_order,
    scan_rmp_phase_order,
    scan_rmp_resolution_convergence,
    compare_cyna_fixed_points_for_component,
    deformed_circular_section_rz,
    project_fixed_points_to_deformed_surface,
    find_resonant_components_analytic,
    plot_island_width_bars,
    compute_mn_spectrum,
    plot_mn_heatmap,
    plot_mn_heatmap_radial,
)
from .magnetic_spectrum import (
    IsoThetaBarSpec,
    MAGNETIC_SECTION_OVERLAYS,
    MagneticSectionOverlaySpec,
    PoincareRationalTrace,
    RadialModeSpectrum,
    RationalSurfaceMarker,
    SectionIslandBar,
    SpectrumSurfaceMatrix,
    draw_magnetic_section_overlays,
    draw_magnetic_surface_grid,
    draw_section_xo_points,
    island_bars_on_section,
    magnetic_section_overlay_spec,
    magnetic_section_overlay_specs,
    overlay_island_bars_on_section,
    overlay_poincare_rational_trace,
    overlay_radial_mode_island_bars,
    overlay_radial_resonance_curve,
    overlay_rational_island_bars,
    overlay_rational_surface_markers,
    overlay_surface_resonance_line,
    plot_chirikov_overlaps,
    plot_island_chains_on_section,
    plot_island_phase_scan,
    plot_magnetic_section_overlay_grid,
    plot_radial_mode_heatmap,
    plot_radial_mode_pcolormesh,
    plot_rational_surface_map,
    plot_resonant_radial_profiles,
    plot_spectrum_bar3d,
    plot_spectrum_heatmap,
    plot_spectrum_pcolormesh,
    radial_mode_spectrum,
    rational_surface_markers,
    spectrum_surface_matrix,
)
try:
    from .tokamak_manifold import (
        plot_equilibrium_cross_section,
        plot_poincare_orbits,
        plot_xcycle_marker,
        plot_manifold_1d,
        draw_manifold_segments,
        plot_poincare_manifold_section,
        plot_xcycle_all_manifolds,
        make_tokamak_overview_figure,
        manifold_legend_handles,
        UNSTABLE_CMAPS,
        STABLE_CMAPS,
        PUBLICATION_RC,
    )
except ModuleNotFoundError as exc:
    _TOKAMAK_MANIFOLD_IMPORT_ERROR = exc

    def _tokamak_manifold_unavailable(*args, **kwargs):
        raise ModuleNotFoundError(
            "tokamak manifold plotting requires optional dependencies that are "
            "not available in this environment"
        ) from _TOKAMAK_MANIFOLD_IMPORT_ERROR

    plot_equilibrium_cross_section = _tokamak_manifold_unavailable
    plot_poincare_orbits = _tokamak_manifold_unavailable
    plot_xcycle_marker = _tokamak_manifold_unavailable
    plot_manifold_1d = _tokamak_manifold_unavailable
    draw_manifold_segments = _tokamak_manifold_unavailable
    plot_poincare_manifold_section = _tokamak_manifold_unavailable
    plot_xcycle_all_manifolds = _tokamak_manifold_unavailable
    make_tokamak_overview_figure = _tokamak_manifold_unavailable
    manifold_legend_handles = _tokamak_manifold_unavailable
    UNSTABLE_CMAPS = []
    STABLE_CMAPS = []
    PUBLICATION_RC = {}


_LAZY_VISUAL_MODULES = (
    "boundary_topology",
    "heat_distribution",
    "boundary_optimization",
    "poincare_topology",
)


def __getattr__(name):
    """Resolve specialized visual layers independently on first use."""

    for module_name in _LAZY_VISUAL_MODULES:
        module = import_module(f"{__name__}.{module_name}")
        if name in getattr(module, "__all__", ()):
            value = getattr(module, name)
            globals()[name] = value
            return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

__all__ = [
    "plot_nested_flux_surfaces",
    "BPOL_CMAP",
    "ISLAND_CMAPS",
    "island_fixed_points",
    "compose_magnetic_perturbations",
    "circular_shell_divergence_diagnostic",
    "fieldline_velocity_spectrum_on_circular_surface",
    "rmp_nrmp_mode_rows",
    "sample_stellarator_cylindrical_field",
    "radial_rmp_field_template",
    "DivergenceDiagnostic",
    "FieldlineVelocitySpectrum",
    "CoupledFixedPointSweep",
    "NonResonantContributionRow",
    "NonResonantFieldlineResponse",
    "NonResonantResidualOrderScan",
    "LogLogOrderFit",
    "RMPnRMPModeRow",
    "RMPAmplitudeOrderScan",
    "RMPPhaseOrderScan",
    "RMPResolutionConvergenceRow",
    "RMPResolutionConvergenceScan",
    "ResonantComponent",
    "SurfaceMapResidual",
    "FixedPointPhaseComparison",
    "DeformedFixedPointProjection",
    "deformed_surface_map_residual",
    "loglog_order_fit",
    "plot_perturbation_order_summary",
    "rmp_fixed_point_seeds",
    "rmp_closure_map_span",
    "scan_nonresonant_residual_order",
    "scan_coupled_fixed_point_sweep",
    "scan_rmp_amplitude_order",
    "scan_rmp_phase_order",
    "scan_rmp_resolution_convergence",
    "compare_cyna_fixed_points_for_component",
    "deformed_circular_section_rz",
    "project_fixed_points_to_deformed_surface",
    "find_resonant_components_analytic",
    "plot_island_width_bars",
    "compute_mn_spectrum",
    "plot_mn_heatmap",
    "plot_mn_heatmap_radial",
    "IsoThetaBarSpec",
    "MAGNETIC_SECTION_OVERLAYS",
    "MagneticSectionOverlaySpec",
    "PoincareRationalTrace",
    "RadialModeSpectrum",
    "RationalSurfaceMarker",
    "SectionIslandBar",
    "SpectrumSurfaceMatrix",
    "draw_magnetic_section_overlays",
    "draw_magnetic_surface_grid",
    "draw_section_xo_points",
    "island_bars_on_section",
    "magnetic_section_overlay_spec",
    "magnetic_section_overlay_specs",
    "overlay_island_bars_on_section",
    "overlay_poincare_rational_trace",
    "overlay_radial_mode_island_bars",
    "overlay_radial_resonance_curve",
    "overlay_rational_island_bars",
    "overlay_rational_surface_markers",
    "overlay_surface_resonance_line",
    "plot_chirikov_overlaps",
    "plot_island_chains_on_section",
    "plot_island_phase_scan",
    "plot_magnetic_section_overlay_grid",
    "plot_radial_mode_heatmap",
    "plot_radial_mode_pcolormesh",
    "plot_rational_surface_map",
    "plot_resonant_radial_profiles",
    "plot_spectrum_bar3d",
    "plot_spectrum_heatmap",
    "plot_spectrum_pcolormesh",
    "radial_mode_spectrum",
    "rational_surface_markers",
    "spectrum_surface_matrix",
    "BoundaryTopologyComparisonSummary",
    "DPKRecurrenceProfile",
    "boundary_dpk_recurrence_profile",
    "boundary_topology_comparison_summary",
    "plot_boundary_dpk_recurrence_profile",
    "plot_boundary_topology_comparison",
    "plot_heat_distribution_control_history",
    "plot_heat_distribution_control_result",
    "BoundaryResponseOptimizationObservableRow",
    "BoundaryResponseOptimizationSummary",
    "boundary_response_optimization_summary",
    "plot_boundary_response_optimization_history",
    "PoincareCurvedIslandBar",
    "PoincareDPKClassification",
    "PoincareFixedPointValidation",
    "PoincareIslandSecondaryCoordinates",
    "PoincareTopologyFigureStyle",
    "PoincareTopologyReportPayload",
    "PoincareTraceQuality",
    "circular_flux_coordinate_island_bars",
    "draw_poincare_curved_island_bars",
    "draw_poincare_phase_response_arrows",
    "draw_poincare_island_secondary_contours",
    "draw_poincare_island_secondary_points",
    "draw_poincare_island_secondary_trace_lines",
    "fixed_point_phase_comparison_markers",
    "fixed_point_centered_island_bars",
    "plot_poincare_topology_map",
    "plot_poincare_topology_payload_map",
    "plot_poincare_topology_payload_report",
    "plot_poincare_topology_report",
    "poincare_dpk_classification",
    "poincare_fixed_point_validation",
    "poincare_island_secondary_coordinates",
    "poincare_phase_response_radial_deltas",
    "poincare_topology_report_payload",
    "poincare_trace_index_from_counts",
    "poincare_trace_quality",
    "sample_fixed_s_theta_curve",
    "plot_equilibrium_cross_section",
    "plot_poincare_orbits",
    "plot_xcycle_marker",
    "plot_manifold_1d",
    "draw_manifold_segments",
    "plot_poincare_manifold_section",
    "plot_xcycle_all_manifolds",
    "make_tokamak_overview_figure",
    "manifold_legend_handles",
    "UNSTABLE_CMAPS",
    "STABLE_CMAPS",
    "PUBLICATION_RC",
]
