import json

nb_path = 'D:/Repo/pyna/notebooks/tutorials/stellarator_island_control.ipynb'

with open(nb_path, encoding='utf-8') as f:
    nb = json.load(f)

new_cell_source = [
    "# === Manifold Visualization ===\n",
    "from pyna.topo.variational import PoincareMapVariationalEquations\n",
    "from pyna.topo.manifold_improve import StableManifold, UnstableManifold\n",
    "from pyna.toroidal.visual.tokamak_manifold import _manifold_line_collection, manifold_legend_handles\n",
    "from matplotlib.colors import Normalize\n",
    "import matplotlib.cm as cm\n",
    "\n",
    "# Convert field_func to (dR/dphi, dZ/dphi) form\n",
    "def field_func_2d(R, Z, phi):\n",
    "    tang = stella.field_func(np.array([R, Z, phi]))\n",
    "    dphi_ds = tang[2]\n",
    "    if abs(dphi_ds) < 1e-15:\n",
    "        return np.array([0.0, 0.0])\n",
    "    return np.array([tang[0]/dphi_ds, tang[1]/dphi_ds])\n",
    "\n",
    "# Estimate X-point location\n",
    "psi_res_target = stella.resonant_psi(TARGET_M, TARGET_N)[0]\n",
    "r_res = np.sqrt(psi_res_target) * stella.r0\n",
    "theta_X0 = np.pi/TARGET_M  # first X-point\n",
    "R_xpt = stella.R0 + r_res * np.cos(theta_X0)\n",
    "Z_xpt = r_res * np.sin(theta_X0)\n",
    "print(f'X-point estimate: R={R_xpt:.4f}, Z={Z_xpt:.4f}')\n",
    "\n",
    "# Monodromy matrix\n",
    "print('Computing monodromy matrix...')\n",
    "vq = PoincareMapVariationalEquations(field_func_2d, fd_eps=1e-5)\n",
    "M = vq.jacobian_matrix([R_xpt, Z_xpt], phi_span=(0, 2*np.pi))\n",
    "eigvals = np.linalg.eigvals(M)\n",
    "print(f'Monodromy eigenvalues: {eigvals}')\n",
    "print(f'  |lambda_1|={abs(eigvals[0]):.4f}, |lambda_2|={abs(eigvals[1]):.4f}  (product~1: {abs(eigvals[0]*eigvals[1]):.4f})')\n",
    "\n",
    "# Grow manifolds\n",
    "print('Growing manifolds...')\n",
    "sm_mfld = StableManifold([R_xpt, Z_xpt], M, field_func_2d)\n",
    "um_mfld = UnstableManifold([R_xpt, Z_xpt], M, field_func_2d)\n",
    "sm_mfld.grow(n_turns=10, init_length=5e-5, n_init_pts=6, both_sides=True)\n",
    "um_mfld.grow(n_turns=10, init_length=5e-5, n_init_pts=6, both_sides=True)\n",
    "print(f'Stable: {len(sm_mfld.segments)} segments, Unstable: {len(um_mfld.segments)} segments')\n",
    "\n",
    "# Combined figure\n",
    "fig, ax = plt.subplots(figsize=(8, 8))\n",
    "ax.set_facecolor('white')\n",
    "\n",
    "# Poincare scatter background\n",
    "if len(results_natural) > 0:\n",
    "    R_pts, Z_pts = results_natural[:, 0], results_natural[:, 1]\n",
    "    psi_pts = ((R_pts - stella.R0)**2 + Z_pts**2) / stella.r0**2\n",
    "    psi_n = np.clip(psi_pts, 0, 1.0)\n",
    "    colors_sc = cm.plasma(psi_n * 0.85 + 0.05)\n",
    "    ax.scatter(R_pts, Z_pts, s=0.6, c=colors_sc, rasterized=True, alpha=0.5, zorder=2)\n",
    "\n",
    "# Manifolds with arc-length coloring\n",
    "for seg in sm_mfld.segments:\n",
    "    if len(seg) > 2:\n",
    "        lc, _ = _manifold_line_collection(seg, cmap='GnBu')\n",
    "        lc.set_linewidth(1.2); lc.set_alpha(0.9); lc.set_zorder(6)\n",
    "        ax.add_collection(lc)\n",
    "\n",
    "for seg in um_mfld.segments:\n",
    "    if len(seg) > 2:\n",
    "        lc, _ = _manifold_line_collection(seg, cmap='Oranges')\n",
    "        lc.set_linewidth(1.2); lc.set_alpha(0.9); lc.set_zorder(6)\n",
    "        ax.add_collection(lc)\n",
    "\n",
    "# X-point marker\n",
    "ax.plot(R_xpt, Z_xpt, 'r+', ms=12, mew=2.5, zorder=8, label='X-point')\n",
    "\n",
    "# Resonant surface\n",
    "theta_c = np.linspace(0, 2*np.pi, 300)\n",
    "ax.plot(stella.R0 + r_res*np.cos(theta_c), r_res*np.sin(theta_c),\n",
    "        '--', color='tomato', lw=0.8, alpha=0.6, label=f'q={TARGET_M}/{TARGET_N} surface')\n",
    "ax.plot(stella.R0 + stella.r0*np.cos(theta_c), stella.r0*np.sin(theta_c),\n",
    "        'k-', lw=1.2, label='LCFS')\n",
    "\n",
    "# Colorbar + legend\n",
    "sm_cb = plt.cm.ScalarMappable(cmap='plasma', norm=Normalize(0,1))\n",
    "sm_cb.set_array([])\n",
    "cbar = plt.colorbar(sm_cb, ax=ax, fraction=0.04, pad=0.04)\n",
    "cbar.set_label(r'$\\psi_\\mathrm{norm}$', fontsize=11)\n",
    "\n",
    "mfld_handles = manifold_legend_handles('Oranges', 'GnBu')\n",
    "ax.legend(handles=mfld_handles + [\n",
    "    plt.Line2D([0],[0], marker='+', color='r', ms=10, mew=2, lw=0, label='X-point'),\n",
    "    plt.Line2D([0],[0], color='k', lw=1.2, label='LCFS'),\n",
    "], loc='upper right', fontsize=9, framealpha=0.9)\n",
    "\n",
    "ax.set_xlim(stella.R0 - 1.15*stella.r0, stella.R0 + 1.15*stella.r0)\n",
    "ax.set_ylim(-1.15*stella.r0, 1.15*stella.r0)\n",
    "ax.set_xlabel('$R$ (m)', fontsize=11)\n",
    "ax.set_ylabel('$Z$ (m)', fontsize=11)\n",
    "ax.set_title(f'Poincar\\u00e9 map + Stable/Unstable Manifolds\\n'\n",
    "             f'q={TARGET_M}/{TARGET_N} island, $\\\\phi=0$', fontsize=12)\n",
    "ax.set_aspect('equal')\n",
    "plt.tight_layout()\n",
    "plt.savefig('poincare_manifolds.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "print('Done.')\n",
]

new_cell = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": new_cell_source,
}

# Insert after cell 6
nb['cells'].insert(7, new_cell)

with open(nb_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f'Done. Total cells: {len(nb["cells"])}')
