name: Sphinx to Github pages
on: [push, pull_request, workflow_dispatch]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Sphinx docs to GitHub Pages
        uses: uibcdf/action-sphinx-docs-to-gh-pages@v1.0.0
